[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    madhephaestus/ESP32Servo @ ^3.0.5
    bblanchon/ArduinoJson @ ^7.0.4
    tzapu/WiFiManager @ ^2.0.17
